<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
    <Using Include="Xunit" />
    <ProjectReference Include="..\..\src\Pipeline.Contracts\Pipeline.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Requirements.Collector\Requirements.Collector.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
